# Generated by Django 4.2.1 on 2023-05-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animao', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.URLField(),
        ),
    ]
